export function mergeWithDefaults(localizer: any, culture: any, formatOverrides: any, messages: any): any;
export class DateLocalizer {
    constructor(spec: any);
    propType: any;
    formats: any;
    format: (...args: any[]) => any;
    startOfWeek: any;
    merge: any;
    inRange: any;
    lt: any;
    lte: any;
    gt: any;
    gte: any;
    eq: any;
    neq: any;
    startOf: any;
    endOf: any;
    add: any;
    range: any;
    diff: any;
    ceil: any;
    min: any;
    max: any;
    minutes: any;
    daySpan: any;
    firstVisibleDay: any;
    lastVisibleDay: any;
    visibleDays: any;
    getSlotDate: any;
    getTimezoneOffset: any;
    getDstOffset: any;
    getTotalMin: any;
    getMinutesFromMidnight: any;
    continuesPrior: any;
    continuesAfter: any;
    sortEvents: any;
    inEventRange: any;
    isSameDate: any;
    startAndEndAreDateOnly: any;
    segmentOffset: any;
}
